---
- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:               # LIST OF DIRECTORIESS TO MAKE we can include a file in this program with the json later if wanted
    - "{{ ansible_env.HOME }}/{{ client_name }}"
    - "{{ ansible_env.HOME }}/{{ client_name }}/nmap"
    - "{{ ansible_env.HOME }}/{{ client_name }}/tools"
    - "{{ ansible_env.HOME }}/{{ client_name }}/output"