---
- name: "Microsoft Outlook.py into ansible :)"
  hosts: localhost
  connection: local

  roles:
    - role: "roles/updates"
    - role: "roles/setconfs"
      vars:
        users:
          - username: "{{ ansible_user_id }}"
    # role for zsh and theme for zsh?


